Repository Blazored/Typeahead, pull requests merged in 2021-01, with the labels that each got.

#191 Added a check so reselecting the current selection doesnt update Value
  samples/BlazorWebAssembly/Pages/Index.razor
  src/Blazored.Typeahead/BlazoredTypeahead.razor.cs
Labels: Bug

#192 Added DisableClear parameter to hide clear button
  README.md
  src/Blazored.Typeahead/BlazoredTypeahead.razor
  src/Blazored.Typeahead/BlazoredTypeahead.razor.cs
Labels: Feature

#173 Update BlazoredTypeahead.razor
  src/Blazored.Typeahead/BlazoredTypeahead.razor
Labels: Maintenance

#193 Added check to only show dropdown icon on disabled control when dropdown mode is active
  src/Blazored.Typeahead/BlazoredTypeahead.razor
  src/Blazored.Typeahead/wwwroot/blazored-typeahead.css
Labels: Bug

#194 Docs for using the convert method
  README.md
Labels: Docs

#195 Click event handler to control resetting the component
  src/Blazored.Typeahead/BlazoredTypeahead.razor
  src/Blazored.Typeahead/BlazoredTypeahead.razor.cs
  src/Blazored.Typeahead/Interop.cs
  src/Blazored.Typeahead/wwwroot/blazored-typeahead.js
Labels: Bug
